<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>CDC Data Exercise – Shaun van den Hurk’s Data Analysis Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-df479d6c4d77d0e0dfbcb5361179d7fd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Shaun van den Hurk’s Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.qmd">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.qmd">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Shaunvet/ShaunvandenHurk-MADA-portfolio.git"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CDC Data Exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="cdc-data-exercise" class="level1">
<h1>CDC Data Exercise</h1>
<p>This dataset was sourced from the data repositories on the CDC website. This data evaluates the weekly hospitalization metrics for viral respiratory infections by jurisdiction in the United States from the mandatory reporting periods of August 1, 2020 to April 30, 2024, and then some voluntary reporting from May 1, 2024 - October 31, 2024. The data focuses on viral respiratory hospitalizations, primarily COVID-19 and influenza, and is derived from the National Healthcare Safety Network (NHSN).</p>
<p>The data is reported by week and contains information on the number of hospitals reporting adult COVID-19 adminssions, pediatric COVID-19 admissions, and influenza admissions. It then also provides a number of other variables related to hospital admissions and occupancies (including inpatient and ICU bed occupancies), and this is reported by geographic aggregation (State) and icludes the number of hospitals reporting in that time frame (including the hospital and patient reporting days).</p>
<p>The data can be found at this URL: <a href="https://data.cdc.gov/Public-Health-Surveillance/Weekly-United-States-Hospitalization-Metrics-by-Ju/aemt-mg7g/about_data" class="uri">https://data.cdc.gov/Public-Health-Surveillance/Weekly-United-States-Hospitalization-Metrics-by-Ju/aemt-mg7g/about_data</a></p>
<p>The citation for this data is:</p>
<p>Centers for Disease Control and Prevention, Division of Healthcare Quality Promotion, National Healthcare Safety Network (NHSN), Weekly United States Viral Respiratory Hospitalization, Bed Occupancy, and Bed Capacity Metrics by Jurisdiction, During the Mandatory Hospital Reporting Period from August 1, 2020 to April 30, 2024, and for Data Reported Voluntarily Beginning May 1, 2024 (version date: November 1, 2024).</p>
<section id="evaluating-the-data" class="level2">
<h2 class="anchored" data-anchor-id="evaluating-the-data">Evaluating the data</h2>
<p>First let’s load the required packages for our data analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readr"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us load and get a summary of the CDC dataset. Note that the name of the file was changed at download to have a more user friendly name. Change the name at download to the same name used below or change the name of the file when loading the data to the name We will name this full dataset as cdc_datsset in R and work with that variable name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cdc_dataset <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cdcdata-exercise/cdc_data_weekly_respiratory_hospitalizations_2020-2024.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  ) <span class="co"># MJ: updated to use "here" package, useful for collaboration work </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 12597 Columns: 82
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (1): Geographic aggregation
dbl  (80): Hospital Reporting Days, Percent Hospital Reporting Days, Number ...
date  (1): Week Ending Date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Viewing the dataset and getting a summary</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Week Ending Date     Geographic aggregation Hospital Reporting Days
 Min.   :2020-08-08   Length:12597           Min.   :    0.0        
 1st Qu.:2021-08-28   Class :character       1st Qu.:  204.2        
 Median :2022-09-17   Mode  :character       Median :  474.0        
 Mean   :2022-09-17                          Mean   : 1101.5        
 3rd Qu.:2023-10-07                          3rd Qu.:  797.0        
 Max.   :2024-10-26                          Max.   :33925.0        
                                             NA's   :171            
 Percent Hospital Reporting Days
 Min.   :0.0000                 
 1st Qu.:0.9500                 
 Median :0.9800                 
 Mean   :0.8996                 
 3rd Qu.:1.0000                 
 Max.   :1.0000                 
 NA's   :171                    
 Number Hospitals Reporting Adult COVID-19 Admissions
 Min.   :   0.0                                      
 1st Qu.:  28.0                                      
 Median :  64.0                                      
 Mean   : 157.4                                      
 3rd Qu.: 114.0                                      
 Max.   :4872.0                                      
                                                     
 Number Hospitals Reporting Pediatric COVID-19 Admissions
 Min.   :   0.0                                          
 1st Qu.:  27.0                                          
 Median :  63.0                                          
 Mean   : 156.4                                          
 3rd Qu.: 114.0                                          
 Max.   :4872.0                                          
                                                         
 Number Hospitals Reporting Influenza Admissions
 Min.   :   0.0                                 
 1st Qu.:  24.0                                 
 Median :  58.0                                 
 Mean   : 144.9                                 
 3rd Qu.: 112.0                                 
 Max.   :4872.0                                 
                                                
 Number Hospitals Reporting Prevalent Influenza Hospitalizations
 Min.   :   0.0                                                 
 1st Qu.:  24.0                                                 
 Median :  58.0                                                 
 Mean   : 144.9                                                 
 3rd Qu.: 112.0                                                 
 Max.   :4872.0                                                 
                                                                
 Number Hospitals Reporting Hospitalized Influenza ICU Patients
 Min.   :   0.0                                                
 1st Qu.:  24.0                                                
 Median :  58.0                                                
 Mean   : 144.9                                                
 3rd Qu.: 112.0                                                
 Max.   :4872.0                                                
                                                               
 Number Hospitals Reporting Inpatient Beds Number Hospitals Reporting ICU Beds
 Min.   :   0.0                            Min.   :   0.0                     
 1st Qu.:  28.0                            1st Qu.:  28.0                     
 Median :  63.0                            Median :  63.0                     
 Mean   : 156.7                            Mean   : 157.1                     
 3rd Qu.: 114.0                            3rd Qu.: 114.0                     
 Max.   :4868.0                            Max.   :4872.0                     
                                                                              
 Number Hospitals Reporting Inpatient Beds Occupied
 Min.   :   0.0                                    
 1st Qu.:  28.0                                    
 Median :  63.0                                    
 Mean   : 156.7                                    
 3rd Qu.: 114.0                                    
 Max.   :4868.0                                    
                                                   
 Number Hospitals Reporting ICU Beds Occupied
 Min.   :   0.0                              
 1st Qu.:  27.0                              
 Median :  63.0                              
 Mean   : 155.8                              
 3rd Qu.: 114.0                              
 Max.   :4864.0                              
                                             
 Number Hospitals Reporting Percent Inpatient Bed Occupancy
 Min.   :   0.0                                            
 1st Qu.:  28.0                                            
 Median :  63.0                                            
 Mean   : 156.7                                            
 3rd Qu.: 114.0                                            
 Max.   :4868.0                                            
                                                           
 Number Hospitals Reporting Percent ICU Bed Occupancy
 Min.   :   0.0                                      
 1st Qu.:  27.0                                      
 Median :  63.0                                      
 Mean   : 155.8                                      
 3rd Qu.: 114.0                                      
 Max.   :4864.0                                      
                                                     
 Number Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy
 Min.   :   0.0                                                     
 1st Qu.:  27.0                                                     
 Median :  63.0                                                     
 Mean   : 156.3                                                     
 3rd Qu.: 114.0                                                     
 Max.   :4868.0                                                     
                                                                    
 Number Hospitals Reporting Percent Influenza Inpatient Bed Occupancy
 Min.   :   0.0                                                      
 1st Qu.:  24.0                                                      
 Median :  57.0                                                      
 Mean   : 144.4                                                      
 3rd Qu.: 112.0                                                      
 Max.   :4868.0                                                      
                                                                     
 Number Hospitals Reporting Percent COVID-19 ICU Bed Occupancy
 Min.   :   0.0                                               
 1st Qu.:  27.0                                               
 Median :  63.0                                               
 Mean   : 156.3                                               
 3rd Qu.: 114.0                                               
 Max.   :4872.0                                               
                                                              
 Number Hospitals Reporting Percent Influenza ICU Bed Occupancy
 Min.   :   0.0                                                
 1st Qu.:  24.0                                                
 Median :  57.0                                                
 Mean   : 144.7                                                
 3rd Qu.: 112.0                                                
 Max.   :4872.0                                                
                                                               
 Number Hospitals Reporting Total COVID-19 Admissions
 Min.   :   0.0                                      
 1st Qu.:  28.0                                      
 Median :  64.0                                      
 Mean   : 157.4                                      
 3rd Qu.: 114.0                                      
 Max.   :4872.0                                      
                                                     
 Number Hospitals Reporting Prevalent COVID-19 Hospitalizations
 Min.   :   0                                                  
 1st Qu.:  27                                                  
 Median :  63                                                  
 Mean   : 157                                                  
 3rd Qu.: 114                                                  
 Max.   :4872                                                  
                                                               
 Number Hospitals Reporting Hospitalized COVID-19 ICU Patients
 Min.   :   0.0                                               
 1st Qu.:  27.0                                               
 Median :  63.0                                               
 Mean   : 156.4                                               
 3rd Qu.: 114.0                                               
 Max.   :4872.0                                               
                                                              
 Weekly Average Adult COVID-19 Admissions
 Min.   :    0.00                        
 1st Qu.:    8.71                        
 Median :   28.86                        
 Mean   :  154.91                        
 3rd Qu.:   86.82                        
 Max.   :20271.57                        
 NA's   :263                             
 Weekly Total Adult COVID-19 Admissions
 Min.   :     0.0                      
 1st Qu.:    61.0                      
 Median :   202.0                      
 Mean   :  1084.3                      
 3rd Qu.:   607.8                      
 Max.   :141901.0                      
 NA's   :263                           
 Weekly Average Pediatric COVID-19 Admissions
 Min.   :  0.000                             
 1st Qu.:  0.290                             
 Median :  1.140                             
 Mean   :  5.356                             
 3rd Qu.:  3.140                             
 Max.   :907.140                             
 NA's   :272                                 
 Weekly Total Pediatric COVID-19 Admissions Weekly Average COVID-19 Admissions
 Min.   :   0.00                            Min.   :    0.00                  
 1st Qu.:   2.00                            1st Qu.:    9.43                  
 Median :   8.00                            Median :   30.14                  
 Mean   :  37.49                            Mean   :  160.27                  
 3rd Qu.:  22.00                            3rd Qu.:   89.57                  
 Max.   :6350.00                            Max.   :21178.71                  
 NA's   :272                                NA's   :263                       
 Weekly Total COVID-19 Admissions Weekly Average Influenza Admissions
 Min.   :     0                   Min.   :   0.00                    
 1st Qu.:    66                   1st Qu.:   0.14                    
 Median :   211                   Median :   1.14                    
 Mean   :  1122                   Mean   :  13.44                    
 3rd Qu.:   627                   3rd Qu.:   4.71                    
 Max.   :148251                   Max.   :3696.00                    
 NA's   :263                      NA's   :778                        
 Weekly Total Influenza Admissions
 Min.   :    0.00                 
 1st Qu.:    1.00                 
 Median :    8.00                 
 Mean   :   94.09                 
 3rd Qu.:   33.00                 
 Max.   :25872.00                 
 NA's   :778                      
 Weekly Average Prevalent COVID-19 Hospitalizations
 Min.   :     0.00                                 
 1st Qu.:    55.86                                 
 Median :   193.64                                 
 Mean   :  1121.83                                 
 3rd Qu.:   600.18                                 
 Max.   :143988.14                                 
 NA's   :263                                       
 Weekly Average Prevalent Influenza Hospitalizations
 Min.   :    0.00                                   
 1st Qu.:    1.00                                   
 Median :    6.29                                   
 Mean   :   70.75                                   
 3rd Qu.:   26.86                                   
 Max.   :15911.71                                   
 NA's   :786                                        
 Weekly Average Hospitalized COVID-19 ICU Patients
 Min.   :    0.00                                 
 1st Qu.:    7.43                                 
 Median :   32.14                                 
 Mean   :  229.82                                 
 3rd Qu.:  117.00                                 
 Max.   :26442.14                                 
 NA's   :274                                      
 Weekly Average Hospitalized Influenza ICU Patients
 Min.   :   0.00                                   
 1st Qu.:   0.00                                   
 Median :   0.86                                   
 Mean   :  11.23                                   
 3rd Qu.:   3.71                                   
 Max.   :2333.71                                   
 NA's   :778                                       
 Weekly Average Inpatient Beds Weekly Average ICU Beds
 Min.   :     7                Min.   :     0.0       
 1st Qu.:  2590                1st Qu.:   332.3       
 Median :  7648                Median :  1052.9       
 Mean   : 22430                Mean   :  3363.7       
 3rd Qu.: 15473                3rd Qu.:  2425.8       
 Max.   :710607                Max.   :113106.0       
 NA's   :263                   NA's   :263            
 Weekly Average Inpatient Beds Occupied Weekly Average ICU Beds Occupied
 Min.   :     0.3                       Min.   :    0.0                 
 1st Qu.:  1891.2                       1st Qu.:  221.7                 
 Median :  5241.7                       Median :  747.6                 
 Mean   : 16707.7                       Mean   : 2370.4                 
 3rd Qu.: 11438.7                       3rd Qu.: 1570.2                 
 Max.   :538750.1                       Max.   :82660.3                 
 NA's   :263                            NA's   :278                     
 Weekly Average Percent Inpatient Bed Occupancy
 Min.   :0.0400                                
 1st Qu.:0.6700                                
 Median :0.7300                                
 Mean   :0.7187                                
 3rd Qu.:0.7900                                
 Max.   :1.0900                                
 NA's   :263                                   
 Weekly Average Percent ICU Bed Occupancy
 Min.   :0.0000                          
 1st Qu.:0.6300                          
 Median :0.7000                          
 Mean   :0.6823                          
 3rd Qu.:0.7600                          
 Max.   :1.0000                          
 NA's   :309                             
 Weekly Average Percent COVID-19 Inpatient Bed Occupancy
 Min.   :0.00000                                        
 1st Qu.:0.01000                                        
 Median :0.03000                                        
 Mean   :0.04221                                        
 3rd Qu.:0.05000                                        
 Max.   :0.35000                                        
 NA's   :263                                            
 Weekly Average Percent Influenza Inpatient Bed Occupancy
 Min.   :0.0000                                          
 1st Qu.:0.0000                                          
 Median :0.0000                                          
 Mean   :0.0023                                          
 3rd Qu.:0.0000                                          
 Max.   :0.0700                                          
 NA's   :781                                             
 Weekly Average Percent COVID-19 ICU Bed Occupancy
 Min.   :0.00000                                  
 1st Qu.:0.01000                                  
 Median :0.03000                                  
 Mean   :0.05781                                  
 3rd Qu.:0.07000                                  
 Max.   :0.68000                                  
 NA's   :305                                      
 Weekly Average Percent Influenza ICU Bed Occupancy
 Min.   :0.0000                                    
 1st Qu.:0.0000                                    
 Median :0.0000                                    
 Mean   :0.0026                                    
 3rd Qu.:0.0000                                    
 Max.   :0.0900                                    
 NA's   :839                                       
 Percent Adult COVID-19 Admissions Percent Pediatric COVID-19 Admissions
 Min.   :0.0000                    Min.   :0.0000                       
 1st Qu.:0.9500                    1st Qu.:0.0200                       
 Median :0.9700                    Median :0.0300                       
 Mean   :0.9537                    Mean   :0.0454                       
 3rd Qu.:0.9800                    3rd Qu.:0.0500                       
 Max.   :1.0000                    Max.   :1.0000                       
 NA's   :574                       NA's   :574                          
 Percent Hospitals Reporting Adult COVID-19 Admissions
 Min.   :0.0000                                       
 1st Qu.:0.9600                                       
 Median :0.9800                                       
 Mean   :0.8984                                       
 3rd Qu.:1.0000                                       
 Max.   :1.0000                                       
                                                      
 Percent Hospitals Reporting Pediatric COVID-19 Admissions
 Min.   :0.0000                                           
 1st Qu.:0.9600                                           
 Median :0.9800                                           
 Mean   :0.8927                                           
 3rd Qu.:1.0000                                           
 Max.   :1.0000                                           
                                                          
 Percent Hospitals Reporting Influenza Admissions
 Min.   :0.0000                                  
 1st Qu.:0.9200                                  
 Median :0.9700                                  
 Mean   :0.8312                                  
 3rd Qu.:1.0000                                  
 Max.   :1.0000                                  
                                                 
 Percent Hospitals Reporting Prevalent Influenza Hospitalizations
 Min.   :0.0000                                                  
 1st Qu.:0.9200                                                  
 Median :0.9700                                                  
 Mean   :0.8313                                                  
 3rd Qu.:1.0000                                                  
 Max.   :1.0000                                                  
                                                                 
 Percent Hospitals Reporting Hospitalized Influenza ICU Patients
 Min.   :0.0000                                                 
 1st Qu.:0.9200                                                 
 Median :0.9700                                                 
 Mean   :0.8312                                                 
 3rd Qu.:1.0000                                                 
 Max.   :1.0000                                                 
                                                                
 Percent Hospitals Reporting Inpatient Beds
 Min.   :0.0000                            
 1st Qu.:0.9500                            
 Median :0.9800                            
 Mean   :0.8945                            
 3rd Qu.:1.0000                            
 Max.   :1.0000                            
                                           
 Percent Hospitals Reporting ICU Beds
 Min.   :0.0000                      
 1st Qu.:0.9600                      
 Median :0.9800                      
 Mean   :0.8969                      
 3rd Qu.:1.0000                      
 Max.   :1.0000                      
                                     
 Percent Hospitals Reporting Inpatient Beds Occupied
 Min.   :0.0000                                     
 1st Qu.:0.9500                                     
 Median :0.9800                                     
 Mean   :0.8945                                     
 3rd Qu.:1.0000                                     
 Max.   :1.0000                                     
                                                    
 Percent Hospitals Reporting ICU Beds Occupied
 Min.   :0.0000                               
 1st Qu.:0.9500                               
 Median :0.9800                               
 Mean   :0.8881                               
 3rd Qu.:1.0000                               
 Max.   :1.0000                               
                                              
 Percent Hospitals Reporting Percent Inpatient Bed Occupancy
 Min.   :0.0000                                             
 1st Qu.:0.9500                                             
 Median :0.9800                                             
 Mean   :0.8945                                             
 3rd Qu.:1.0000                                             
 Max.   :1.0000                                             
                                                            
 Percent Hospitals Reporting Percent ICU Bed Occupancy
 Min.   :0.0000                                       
 1st Qu.:0.9500                                       
 Median :0.9800                                       
 Mean   :0.8881                                       
 3rd Qu.:1.0000                                       
 Max.   :1.0000                                       
                                                      
 Percent Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy
 Min.   :0.0000                                                      
 1st Qu.:0.9500                                                      
 Median :0.9800                                                      
 Mean   :0.8926                                                      
 3rd Qu.:1.0000                                                      
 Max.   :1.0000                                                      
                                                                     
 Percent Hospitals Reporting Percent Influenza Inpatient Bed Occupancy
 Min.   :0.0000                                                       
 1st Qu.:0.9200                                                       
 Median :0.9700                                                       
 Mean   :0.8293                                                       
 3rd Qu.:1.0000                                                       
 Max.   :1.0000                                                       
                                                                      
 Percent Hospitals Reporting Percent COVID-19 ICU Bed Occupancy
 Min.   :0.0000                                                
 1st Qu.:0.9600                                                
 Median :0.9800                                                
 Mean   :0.8916                                                
 3rd Qu.:1.0000                                                
 Max.   :1.0000                                                
                                                               
 Percent Hospitals Reporting Percent Influenza ICU Bed Occupancy
 Min.   :0.0000                                                 
 1st Qu.:0.9200                                                 
 Median :0.9700                                                 
 Mean   :0.8305                                                 
 3rd Qu.:1.0000                                                 
 Max.   :1.0000                                                 
                                                                
 Percent Hospitals Reporting Total COVID-19 Admissions
 Min.   :0.0000                                       
 1st Qu.:0.9600                                       
 Median :0.9800                                       
 Mean   :0.8985                                       
 3rd Qu.:1.0000                                       
 Max.   :1.0000                                       
                                                      
 Percent Hospitals Reporting Prevalent COVID-19 Hospitalizations
 Min.   :0.0000                                                 
 1st Qu.:0.9600                                                 
 Median :0.9800                                                 
 Mean   :0.8963                                                 
 3rd Qu.:1.0000                                                 
 Max.   :1.0000                                                 
                                                                
 Percent Hospitals Reporting Hospitalized COVID-19 ICU Patients
 Min.   :0.0000                                                
 1st Qu.:0.9600                                                
 Median :0.9800                                                
 Mean   :0.8925                                                
 3rd Qu.:1.0000                                                
 Max.   :1.0000                                                
                                                               
 Absolute Change in the Percent Hospitals Reporting Adult COVID-19 Admissions from Prior Week
 Min.   :-100.0000                                                                           
 1st Qu.:   0.0000                                                                           
 Median :   0.0000                                                                           
 Mean   :  -0.2037                                                                           
 3rd Qu.:   0.0000                                                                           
 Max.   : 100.0000                                                                           
 NA's   :57                                                                                  
 Absolute Change in the Percent Hospitals Reporting Pediatric COVID-19 Admissions from Prior Week
 Min.   :-100.0000                                                                               
 1st Qu.:   0.0000                                                                               
 Median :   0.0000                                                                               
 Mean   :  -0.1778                                                                               
 3rd Qu.:   0.0000                                                                               
 Max.   : 100.0000                                                                               
 NA's   :57                                                                                      
 Absolute Change in the Percent Hospitals Reporting Influenza Admissions from Prior Week
 Min.   :-100.0000                                                                      
 1st Qu.:   0.0000                                                                      
 Median :   0.0000                                                                      
 Mean   :   0.1491                                                                      
 3rd Qu.:   0.0000                                                                      
 Max.   : 100.0000                                                                      
 NA's   :57                                                                             
 Absolute Change in the Percent Hospitals Reporting Prevalent Influenza Hospitalizations from Prior Week
 Min.   :-100.0000                                                                                      
 1st Qu.:   0.0000                                                                                      
 Median :   0.0000                                                                                      
 Mean   :   0.1487                                                                                      
 3rd Qu.:   0.0000                                                                                      
 Max.   : 100.0000                                                                                      
 NA's   :57                                                                                             
 Absolute Change in the Percent Hospitals Reporting Hospitalized Influenza ICU Patients from Prior Week
 Min.   :-100.0000                                                                                     
 1st Qu.:   0.0000                                                                                     
 Median :   0.0000                                                                                     
 Mean   :   0.1485                                                                                     
 3rd Qu.:   0.0000                                                                                     
 Max.   : 100.0000                                                                                     
 NA's   :57                                                                                            
 Absolute Change in the Percent Hospitals Reporting Inpatient Beds from Prior Week
 Min.   :-100.0000                                                                
 1st Qu.:   0.0000                                                                
 Median :   0.0000                                                                
 Mean   :  -0.2326                                                                
 3rd Qu.:   0.0000                                                                
 Max.   : 100.0000                                                                
 NA's   :57                                                                       
 Absolute Change in the Percent Hospitals Reporting ICU Beds from Prior Week
 Min.   :-100.0000                                                          
 1st Qu.:   0.0000                                                          
 Median :   0.0000                                                          
 Mean   :  -0.2561                                                          
 3rd Qu.:   0.0000                                                          
 Max.   : 100.0000                                                          
 NA's   :57                                                                 
 Absolute Change in the Percent Hospitals Reporting Inpatient Beds Occupied from Prior Week
 Min.   :-100.0000                                                                         
 1st Qu.:   0.0000                                                                         
 Median :   0.0000                                                                         
 Mean   :  -0.2326                                                                         
 3rd Qu.:   0.0000                                                                         
 Max.   : 100.0000                                                                         
 NA's   :57                                                                                
 Absolute Change in the Percent Hospitals Reporting ICU Beds Occupied from Prior Week
 Min.   :-100.0000                                                                   
 1st Qu.:   0.0000                                                                   
 Median :   0.0000                                                                   
 Mean   :  -0.1627                                                                   
 3rd Qu.:   0.0000                                                                   
 Max.   : 100.0000                                                                   
 NA's   :57                                                                          
 Absolute Change in the Percent Hospitals Reporting Percent Inpatient Bed Occupancy from Prior Week
 Min.   :-100.0000                                                                                 
 1st Qu.:   0.0000                                                                                 
 Median :   0.0000                                                                                 
 Mean   :  -0.2326                                                                                 
 3rd Qu.:   0.0000                                                                                 
 Max.   : 100.0000                                                                                 
 NA's   :57                                                                                        
 Absolute Change in the Percent Hospitals Reporting Percent ICU Bed Occupancy from Prior Week
 Min.   :-100.0000                                                                           
 1st Qu.:   0.0000                                                                           
 Median :   0.0000                                                                           
 Mean   :  -0.1627                                                                           
 3rd Qu.:   0.0000                                                                           
 Max.   : 100.0000                                                                           
 NA's   :57                                                                                  
 Absolute Change in the Percent Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy from Prior Week
 Min.   :-100.0000                                                                                          
 1st Qu.:   0.0000                                                                                          
 Median :   0.0000                                                                                          
 Mean   :  -0.1973                                                                                          
 3rd Qu.:   0.0000                                                                                          
 Max.   : 100.0000                                                                                          
 NA's   :57                                                                                                 
 Absolute Change in the Percent Hospitals Reporting Percent Influenza Inpatient Bed Occupancy from Prior Week
 Min.   :-100.0000                                                                                           
 1st Qu.:   0.0000                                                                                           
 Median :   0.0000                                                                                           
 Mean   :   0.1487                                                                                           
 3rd Qu.:   0.0000                                                                                           
 Max.   : 100.0000                                                                                           
 NA's   :57                                                                                                  
 Absolute Change in the Percent Hospitals Reporting Percent COVID-19 ICU Bed Occupancy from Prior Week
 Min.   :-100.000                                                                                     
 1st Qu.:   0.000                                                                                     
 Median :   0.000                                                                                     
 Mean   :  -0.195                                                                                     
 3rd Qu.:   0.000                                                                                     
 Max.   : 100.000                                                                                     
 NA's   :57                                                                                           
 Absolute Change in the Percent Hospitals Reporting Percent Influenza ICU Bed Occupancy from Prior Week
 Min.   :-100.000                                                                                      
 1st Qu.:   0.000                                                                                      
 Median :   0.000                                                                                      
 Mean   :   0.142                                                                                      
 3rd Qu.:   0.000                                                                                      
 Max.   : 100.000                                                                                      
 NA's   :57                                                                                            
 Absolute Change in the Percent Hospitals Reporting Total COVID-19 Admissions from Prior Week
 Min.   :-100.0000                                                                           
 1st Qu.:   0.0000                                                                           
 Median :   0.0000                                                                           
 Mean   :  -0.2091                                                                           
 3rd Qu.:   0.0000                                                                           
 Max.   : 100.0000                                                                           
 NA's   :57                                                                                  
 Absolute Change in the Percent Hospitals Reporting Prevalent COVID-19 Hospitalizations from Prior Week
 Min.   :-100.0000                                                                                     
 1st Qu.:   0.0000                                                                                     
 Median :   0.0000                                                                                     
 Mean   :  -0.2261                                                                                     
 3rd Qu.:   0.0000                                                                                     
 Max.   : 100.0000                                                                                     
 NA's   :57                                                                                            
 Absolute Change in the Percent Hospitals Reporting Hospitalized COVID-19 ICU Patients from Prior Week
 Min.   :-100.000                                                                                     
 1st Qu.:   0.000                                                                                     
 Median :   0.000                                                                                     
 Mean   :  -0.201                                                                                     
 3rd Qu.:   0.000                                                                                     
 Max.   : 100.000                                                                                     
 NA's   :57                                                                                           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(cdc_dataset)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cdc_dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,597 × 82
   `Week Ending Date` `Geographic aggregation` `Hospital Reporting Days`
   &lt;date&gt;             &lt;chr&gt;                                        &lt;dbl&gt;
 1 2020-08-08         AK                                              98
 2 2020-08-15         AK                                              98
 3 2020-08-22         AK                                              98
 4 2020-08-29         AK                                              97
 5 2020-09-05         AK                                              97
 6 2020-09-12         AK                                              98
 7 2020-09-19         AK                                              98
 8 2020-09-26         AK                                              96
 9 2020-10-03         AK                                              97
10 2020-10-10         AK                                              98
# ℹ 12,587 more rows
# ℹ 79 more variables: `Percent Hospital Reporting Days` &lt;dbl&gt;,
#   `Number Hospitals Reporting Adult COVID-19 Admissions` &lt;dbl&gt;,
#   `Number Hospitals Reporting Pediatric COVID-19 Admissions` &lt;dbl&gt;,
#   `Number Hospitals Reporting Influenza Admissions` &lt;dbl&gt;,
#   `Number Hospitals Reporting Prevalent Influenza Hospitalizations` &lt;dbl&gt;,
#   `Number Hospitals Reporting Hospitalized Influenza ICU Patients` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>The summary of the dataset is valuable but it helps to actually view and scroll through the data for a better overview and feel of the data.</p>
<p>We can see that this is a very large dataset. There are 12597 observations in this dataset and 82 columns. We have to do a lot of scrolling to see much, including our summary, which is not very helpful. This is very big for us to evaluate and so we might want to cut it down a bit before we spend time filtering through and cleaning all of the data that is not of interest to us.</p>
<p>For this evaluation we want to have an idea of how COVID-19 and infuenza affected the population by evaluating the hospitilization rates. We are interested in knowing how this affected the healthcare system so we will include the information related to how many hospitals reported data and the occupancy of these hospitals. From viewing the data there seems to be overlap and repetition of some of the data, as well as categories and definitions that are not necessary for us, so we will reduce our columns to those of greatest interest to us. We will focus on adult data as the reporting of pediatric data seems to be limited to COVID-19 and thus will limit any comparisons to influenza.</p>
<p>We are also not going to split up ICU vs general admissions for our evaluations, but this is something that could be broken down.</p>
<p>We will also cut down our observations by focusing on one State and by defining our time frame.</p>
<p>This part could be done in either order and the State and time frame could be adapted.</p>
<p>Cutting down our dataset: Since we know that the mandatory reporting period will have the best information reported, we will focus on this time frame August 1, 2020 - April 30, 2024. We will also start by focusing on the state of Georgia (region=GA). We will use the filter function to get the rows with these variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the filter function to select for our rows of interest. We will assign these to two new variables.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter by State = selecting GA</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cdc_data_georgia <span class="ot">&lt;-</span> cdc_dataset <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">Geographic aggregation</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"GA"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter further by date = August 1, 2020 - April 30, 2024</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>cdc_georgia_mandatory_data <span class="ot">&lt;-</span> cdc_data_georgia <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="st">`</span><span class="at">Week Ending Date</span><span class="st">`</span><span class="sc">&gt;=</span><span class="st">"2020-08-01"</span> <span class="sc">&amp;</span> <span class="st">`</span><span class="at">Week Ending Date</span><span class="st">`</span> <span class="sc">&lt;=</span> <span class="st">"2024-04-30"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see that we have filtered our observations down to 195 observations. We could do the same thing for multiple states (or have included multiple states) and compared the data between states.</p>
<p>Now we will focus on selecting the columns that we are most interested in: We will use the select function. Columns of interest to be kept: - Week Ending Date - Geographic aggregation - Number Hospitals Reporting Adult COVID-19 Admissions - Number Hospitals Reporting Influenza Admissions - Weekly Total Adult COVID-19 Admissions - Weekly Total Influenza Admissions - Weekly Average Hospitalized COVID-19 ICU Patients - Weekly Average Hospitalized Influenza ICU Patients - Weekly Average Inpatient Beds - Weekly Average ICU Beds - Weekly Average Inpatient Beds Occupied - Weekly Average ICU Beds Occupied</p>
<p>Defining our new dataset with columns of interest:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the select function to define our columns of interest for the GA dataset that we refined</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>cdc_ga_mandatory_refined <span class="ot">&lt;-</span> cdc_georgia_mandatory_data <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">`</span><span class="at">Week Ending Date</span><span class="st">`</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Geographic aggregation</span><span class="st">`</span>, <span class="st">`</span><span class="at">Number Hospitals Reporting Adult COVID-19 Admissions</span><span class="st">`</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Total Adult COVID-19 Admissions</span><span class="st">`</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Average Hospitalized COVID-19 ICU Patients</span><span class="st">`</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Average Hospitalized Influenza ICU Patients</span><span class="st">`</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Average Inpatient Beds</span><span class="st">`</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Average ICU Beds</span><span class="st">`</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Average Inpatient Beds Occupied</span><span class="st">`</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">Weekly Average ICU Beds Occupied</span><span class="st">`</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co">#View the new datset and a summary</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Week Ending Date     Geographic aggregation
 Min.   :2020-08-08   Length:195            
 1st Qu.:2021-07-13   Class :character      
 Median :2022-06-18   Mode  :character      
 Mean   :2022-06-18                         
 3rd Qu.:2023-05-23                         
 Max.   :2024-04-27                         
                                            
 Number Hospitals Reporting Adult COVID-19 Admissions
 Min.   : 87.0                                       
 1st Qu.:137.0                                       
 Median :138.0                                       
 Mean   :137.5                                       
 3rd Qu.:139.0                                       
 Max.   :140.0                                       
                                                     
 Number Hospitals Reporting Influenza Admissions
 Min.   :  0.0                                  
 1st Qu.:134.0                                  
 Median :137.0                                  
 Mean   :127.2                                  
 3rd Qu.:139.0                                  
 Max.   :139.0                                  
                                                
 Weekly Total Adult COVID-19 Admissions Weekly Total Influenza Admissions
 Min.   : 122.0                         Min.   :   0.00                  
 1st Qu.: 410.5                         1st Qu.:  17.00                  
 Median : 816.0                         Median :  30.00                  
 Mean   :1259.5                         Mean   :  73.04                  
 3rd Qu.:1446.5                         3rd Qu.:  54.75                  
 Max.   :5459.0                         Max.   :1123.00                  
                                        NA's   :5                        
 Weekly Average Hospitalized COVID-19 ICU Patients
 Min.   :  28.57                                  
 1st Qu.:  69.64                                  
 Median : 137.29                                  
 Mean   : 283.58                                  
 3rd Qu.: 376.29                                  
 Max.   :1319.86                                  
                                                  
 Weekly Average Hospitalized Influenza ICU Patients
 Min.   :  0.000                                   
 1st Qu.:  2.895                                   
 Median : 31.570                                   
 Mean   : 45.580                                   
 3rd Qu.: 71.395                                   
 Max.   :255.000                                   
 NA's   :5                                         
 Weekly Average Inpatient Beds Weekly Average ICU Beds
 Min.   :12754                 Min.   :2403           
 1st Qu.:17263                 1st Qu.:3007           
 Median :17994                 Median :3043           
 Mean   :18361                 Mean   :3069           
 3rd Qu.:20123                 3rd Qu.:3153           
 Max.   :20852                 Max.   :3422           
                                                      
 Weekly Average Inpatient Beds Occupied Weekly Average ICU Beds Occupied
 Min.   :10065                          Min.   :1210                    
 1st Qu.:13769                          1st Qu.:2315                    
 Median :14365                          Median :2395                    
 Mean   :14415                          Mean   :2377                    
 3rd Qu.:15170                          3rd Qu.:2484                    
 Max.   :16660                          Max.   :2828                    
                                                                        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(cdc_ga_mandatory_refined)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cdc_ga_mandatory_refined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 195 × 12
   `Week Ending Date` `Geographic aggregation` Number Hospitals Reporting Adul…¹
   &lt;date&gt;             &lt;chr&gt;                                                &lt;dbl&gt;
 1 2020-08-08         GA                                                      87
 2 2020-08-15         GA                                                     130
 3 2020-08-22         GA                                                     130
 4 2020-08-29         GA                                                     131
 5 2020-09-05         GA                                                     133
 6 2020-09-12         GA                                                     134
 7 2020-09-19         GA                                                     129
 8 2020-09-26         GA                                                     131
 9 2020-10-03         GA                                                     139
10 2020-10-10         GA                                                     139
# ℹ 185 more rows
# ℹ abbreviated name: ¹​`Number Hospitals Reporting Adult COVID-19 Admissions`
# ℹ 9 more variables: `Number Hospitals Reporting Influenza Admissions` &lt;dbl&gt;,
#   `Weekly Total Adult COVID-19 Admissions` &lt;dbl&gt;,
#   `Weekly Total Influenza Admissions` &lt;dbl&gt;,
#   `Weekly Average Hospitalized COVID-19 ICU Patients` &lt;dbl&gt;,
#   `Weekly Average Hospitalized Influenza ICU Patients` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>We have reduced our datset to a much more manageable set of information that we can refine and evalaute. If we feel that we should incude an additional column (left something valuable out) we can go back and add it now. Our sumamry shows us that we have a few NA values in our datset.</p>
<p>We will look for these using the is.na function. We will create a specific variable from these NA values to make it easier to visualise without searching. In reality, with the summary and reduced size of the dataset we can scroll through and find these if we want. However, printing these specifically allows us to isolate them quickly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cdc_refined_ga_NA <span class="ot">&lt;-</span> cdc_ga_mandatory_refined <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="fu">if_any</span>(<span class="fu">everything</span>(), is.na))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cdc_refined_ga_NA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 12
  `Week Ending Date` `Geographic aggregation` Number Hospitals Reporting Adult…¹
  &lt;date&gt;             &lt;chr&gt;                                                 &lt;dbl&gt;
1 2020-08-08         GA                                                       87
2 2020-08-15         GA                                                      130
3 2020-08-22         GA                                                      130
4 2020-08-29         GA                                                      131
5 2020-10-10         GA                                                      139
# ℹ abbreviated name: ¹​`Number Hospitals Reporting Adult COVID-19 Admissions`
# ℹ 9 more variables: `Number Hospitals Reporting Influenza Admissions` &lt;dbl&gt;,
#   `Weekly Total Adult COVID-19 Admissions` &lt;dbl&gt;,
#   `Weekly Total Influenza Admissions` &lt;dbl&gt;,
#   `Weekly Average Hospitalized COVID-19 ICU Patients` &lt;dbl&gt;,
#   `Weekly Average Hospitalized Influenza ICU Patients` &lt;dbl&gt;,
#   `Weekly Average Inpatient Beds` &lt;dbl&gt;, `Weekly Average ICU Beds` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>We can see that these NA values are in the first four weeks of observations, and one week in October 2020, and that they are all in the influenza observations. We might be led to believe that perhaps the recording/reporting (or testing) of influenza tests was halted in the peak of the COVID-19 pandemic when resources were limited, or that the order to report influenza cases for this use only cae through later. This is something that we might be able to find on the CDC website if desired. We will not delete these observations because we would lose valuable information related to the COVID-19 pandemic from these weeks. We could potentially use synthetic data for these missing variables or we could work on date ranges that do not include these weeks (2020-08-08 - 2020-08-29 and 2020-10-10) if we want to compare COVID-19 to Influenza.</p>
<p>We will make a few plots of different variables. We will start by analyzing the COVID-19 data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the total adult COVID-19 cases  </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>covid_adult_admissions_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Weekly Total Adult COVID-19 Admissions</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>,<span class="at">fill=</span> <span class="st">"green"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of the weekly total adult COVID-19 Hospital Admissions"</span>, <span class="at">x =</span> <span class="st">"Weekly Total Adult COVID-19 Admissions"</span>, <span class="at">y =</span> <span class="st">"Week counts"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(covid_adult_admissions_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will get a summary of this data (Distribution of the weekly total adult COVID-19 Hospital Admissions) and calculate the standard deviation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Total Adult COVID-19 Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  122.0   410.5   816.0  1259.5  1446.5  5459.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Total Adult COVID-19 Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1267.792</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the average hospitalized COVID-19 ICU patients  </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>covid_icu_patients_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Weekly Average Hospitalized COVID-19 ICU Patients</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>,<span class="at">fill=</span> <span class="st">"red"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of the average COVID-19 Hospital ICU Patients"</span>, <span class="at">x =</span> <span class="st">"Weekly Average COVID-19 ICU Patients"</span>, <span class="at">y =</span> <span class="st">"Week counts"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(covid_icu_patients_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will get a summary of this data (Distribution of the average COVID-19 Hospital ICU Patients) and calculate the standard deviation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average Hospitalized COVID-19 ICU Patients</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  28.57   69.64  137.29  283.58  376.29 1319.86 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average Hospitalized COVID-19 ICU Patients</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 315.2279</code></pre>
</div>
</div>
<p>We see how many more patients were hospitalized than were in ICU in Georgia, as the max number for the ICU patients is quite close to mean value of the hospital admissions.</p>
<p>Looking at the same distributions for the Influenza data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the total Influenza cases  </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>influenza_adult_admissions_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>,<span class="at">fill=</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of the weekly Influenza Hospital Admissions"</span>, <span class="at">x =</span> <span class="st">"Weekly Total Influenza Admissions"</span>, <span class="at">y =</span> <span class="st">"Week counts"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(influenza_adult_admissions_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We receive a warning that some values were excluded (likely our NA values).</p>
<p>We will get a summary of this data (Weekly Total Influenza Admissions) and calculate the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00   17.00   30.00   73.04   54.75 1123.00       5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation and exclude the NA values in the influenza data</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 137.6914</code></pre>
</div>
</div>
<p>The mean value for admissions for the influenza cases is a great deal lower than that from the COVID-19 cases. We see that the mean of the COVID-19 hospital admissions is 17.2 times greater than the mean from the influenza admissions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the average influenza ICU patients  </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>influenza_icu_patients_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Weekly Average Hospitalized Influenza ICU Patients</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>,<span class="at">fill=</span> <span class="st">"red"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of the average Influenza Hospital ICU Patients"</span>, <span class="at">x =</span> <span class="st">"Weekly Average Influenza ICU Patients"</span>, <span class="at">y =</span> <span class="st">"Week counts"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(influenza_icu_patients_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We get the same warning as our previous plot for the influenza cases (regarding the missing NA values).</p>
<p>We will get a summary of this data (Weekly Average Influenza ICU Patients) and calculate the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average Hospitalized Influenza ICU Patients</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   2.895  31.570  45.580  71.395 255.000       5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation and exclude the NA values in the influenza data</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average Hospitalized Influenza ICU Patients</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51.3058</code></pre>
</div>
</div>
<p>The mean value for ICU patients for the influenza cases is also much lower than that from the COVID-19 cases (not quite as much compared to admissions). We see that the mean of the COVID-19 hospital admissions is 6.2 times greater than the mean from the influenza ICU patients.</p>
<p>By comparing the plots and summary data we generated for COVID-19 and Influenza cases we can already see the much greater number of hospital admissions and ICU cases from COVID-19 compared to influenza. We also see the wider range for the COVID-19 cases compared to Influenza. The pronounced impact of COVID-19 as a respiratory disease is obvious before we do further analysis.</p>
<p>We can evaluate the strain on the healthcare system by looking at the hospital beds that were occupied (we will just look at total numbers between inpatient and ICU and not as a percentage). This does not distinguish what caused the beds to be occupied.</p>
<p>Looking at the distributions of occupied inptient beds:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the occupied inptient beds  </span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>cdc_inpatient_occupied_beds_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Weekly Average Inpatient Beds Occupied</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>,<span class="at">fill=</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of the weekly Average Occupied Inpatient Beds"</span>, <span class="at">x =</span> <span class="st">"Weekly Inpatient Beds"</span>, <span class="at">y =</span> <span class="st">"Week counts"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cdc_inpatient_occupied_beds_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will get a summary of the inpatient occupied beds data and calculate the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average Inpatient Beds Occupied</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10065   13769   14365   14415   15170   16660 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average Inpatient Beds Occupied</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1097.536</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the occupied ICU beds  </span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>cdc_icu_occupied_beds_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Weekly Average ICU Beds Occupied</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>,<span class="at">fill=</span> <span class="st">"red"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of the weekly Average Occupied ICU Beds"</span>, <span class="at">x =</span> <span class="st">"Weekly Occupied ICU Beds"</span>, <span class="at">y =</span> <span class="st">"Week counts"</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cdc_icu_occupied_beds_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will get a summary of the occupied ICU beds data and calculate the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average ICU Beds Occupied</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1210    2315    2395    2377    2484    2828 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Weekly Average ICU Beds Occupied</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 237.6443</code></pre>
</div>
</div>
<p>We can look at the occupancy of the inpatient hosptial beds by week for the period evaluated, we will generate a line plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are looking at the distribution of the occupied inptient beds over time </span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>cdc_inpatient_beds_time_plot<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cdc_ga_mandatory_refined, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Week Ending Date</span><span class="st">`</span>, <span class="at">y=</span><span class="st">`</span><span class="at">Weekly Average Inpatient Beds Occupied</span><span class="st">`</span>)) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Occupancy of Inpatient Beds over time"</span>, <span class="at">x =</span> <span class="st">"Week Evaluated"</span>, <span class="at">y =</span> <span class="st">"Weekly Occupied Inpatient Beds"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cdc_inpatient_beds_time_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will provide a summary of the number of hospitals reporting COVID-19 and influenza respectively without plotting a graph.</p>
<p>We will get a summary of the number of hospital reporting Adult COVID-19 Admissions and calculate the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Number Hospitals Reporting Adult COVID-19 Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   87.0   137.0   138.0   137.5   139.0   140.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation </span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Number Hospitals Reporting Adult COVID-19 Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.080754</code></pre>
</div>
</div>
<p>We will get a summary of the number of hospital reporting Influenza Admissions and calculate the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    0.0   134.0   137.0   127.2   139.0   139.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation </span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cdc_ga_mandatory_refined<span class="sc">$</span><span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.62036</code></pre>
</div>
</div>
<p>We see very similar values for influenza and COVID-19, although we realize that the 0 values in the influenza cases might be an artifact carried by the original creators from the NA values. We will create a new variable looking at the number of hospitals reporting influenza cases without these entries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We are using a loop function to first select for rows where there are no NA values, this is based on using one of the columns that we previously saw had an NA value. We then select the rows to only keep the influenza data</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>filtered_infuenza_cases<span class="ot">&lt;-</span> cdc_ga_mandatory_refined <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">`</span><span class="at">Week Ending Date</span><span class="st">`</span>, <span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>, <span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>,<span class="st">`</span><span class="at">Weekly Average Hospitalized Influenza ICU Patients</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now run the previous summary of the influenza reported cases by hospitals again and compare results</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(filtered_infuenza_cases<span class="sc">$</span><span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0   135.0   137.0   130.6   139.0   139.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">#We will calculate the standard deviation </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(filtered_infuenza_cases<span class="sc">$</span><span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.22654</code></pre>
</div>
</div>
<p>We see that the values did change, with the standard deviation decreasing by around 7, but it perhaps did not decrease by as much as expected because the minimum value is now 1 instead of 0.</p>
</section>
</section>
<section id="part-2" class="level1">
<h1>Part 2</h1>
<p>This section contributed by Murphy John.</p>
<section id="some-further-eda" class="level2">
<h2 class="anchored" data-anchor-id="some-further-eda">Some further EDA</h2>
<p>Variables:</p>
<ul>
<li><p>Week Ending Date: from 2020-08-08 to 2024-04-27</p></li>
<li><p>Geographic Aggregation: GA</p></li>
<li><p>Number Hospitals Reporting Adult COVID-19 Admissions: Min: 87, Mean: 137.5, Max: 140,</p></li>
<li><p>Number Hospitals Reporting Influenza Admissions: Min: 0, Mean: 127.2, Max: 139</p></li>
<li><p>Weekly Total Adult COVID-19 Admissions: Min: 122, Mean: 1259.5, Max: 5459</p></li>
<li><p>Weekly Total Influenza Admissions: Min: 0, Mean: 73.04, Max: 1123</p></li>
<li><p>Weekly Average Hospitalized COVID-19 ICU Patients: Min: 28.57, Mean: 283.58, Max: 1319.86</p></li>
<li><p>Weekly Average Hospitalized Influenza ICU Patients: Min: 0, Mean: 45.58, Max: 255</p></li>
<li><p>Weekly Average Inpatient Beds: Min: 12754, Mean: 18361, Max: 20852</p></li>
<li><p>Weekly Average ICU Beds: Min: 2403, Mean: 3043, Max: 3422</p></li>
<li><p>Weekly Average Inpatient Beds Occupied: Min: 10065, Mean: 14415, Max: 16660</p></li>
<li><p>Weekly Average ICU Beds Occupied: Min: 1210, Mean: 2377, Max: 2828</p></li>
</ul>
<p>It seems plausible that many of these variables will be associated with time due to the COVID-19 pandemic and general fluctuations of the influenza season. Explore the changes over time for all variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rename variables for working convenience</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> cdc_ga_mandatory_refined <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="st">`</span><span class="at">Week Ending Date</span><span class="st">`</span>,</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="st">`</span><span class="at">Geographic aggregation</span><span class="st">`</span>,</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hosp_report_covid =</span> <span class="st">`</span><span class="at">Number Hospitals Reporting Adult COVID-19 Admissions</span><span class="st">`</span>,</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">hosp_report_flu =</span> <span class="st">`</span><span class="at">Number Hospitals Reporting Influenza Admissions</span><span class="st">`</span>,</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_covid_admin =</span> <span class="st">`</span><span class="at">Weekly Total Adult COVID-19 Admissions</span><span class="st">`</span>,</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_flu_admin =</span> <span class="st">`</span><span class="at">Weekly Total Influenza Admissions</span><span class="st">`</span>,</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_hosp_covid =</span> <span class="st">`</span><span class="at">Weekly Average Hospitalized COVID-19 ICU Patients</span><span class="st">`</span>,</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_hosp_flu =</span> <span class="st">`</span><span class="at">Weekly Average Hospitalized Influenza ICU Patients</span><span class="st">`</span>,</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_inpat_bed =</span> <span class="st">`</span><span class="at">Weekly Average Inpatient Beds</span><span class="st">`</span>,</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_icu_bed =</span> <span class="st">`</span><span class="at">Weekly Average ICU Beds</span><span class="st">`</span>,</span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_inpat_bed_ocp =</span> <span class="st">`</span><span class="at">Weekly Average Inpatient Beds Occupied</span><span class="st">`</span>,</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_icu_bed_ocp =</span> <span class="st">`</span><span class="at">Weekly Average ICU Beds Occupied</span><span class="st">`</span></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by reporting COVID hospitals</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>hosp_report_covid)  </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># One outlier of 87 in the first week (2020-08-08)  </span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>hosp_report_covid, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">130</span>, <span class="dv">140</span>))  </span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Constant at 139, drops off at the end to about 138, 137, 136, 134  </span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by reporting flu hospitals</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>hosp_report_flu)  </span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a><span class="co"># First 11 observations are between 0-2  </span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>hosp_report_flu, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">140</span>))  </span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Cluster around 120-125 from 08-2021 to 01-2022  </span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>hosp_report_flu, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">130</span>, <span class="dv">140</span>))  </span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Constant at 139 in 2021-2022, then drops to 138, 137, and 134  </span></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by number of COVID admissions</span></span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>num_covid_admin)  </span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Clear spikes: Jan-Feb 2021, Aug-Sep 2021, Jan 2022  </span></span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Smaller spikes: Jul-Aug 2022, Jan 2023  </span></span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by number of flu admissions</span></span>
<span id="cb66-21"><a href="#cb66-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>num_flu_admin)  </span>
<span id="cb66-22"><a href="#cb66-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Peaks in January: 25 (2021), 50 (2022), 80 (2023), 250 (2023), 800 (2024)  </span></span>
<span id="cb66-23"><a href="#cb66-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-24"><a href="#cb66-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by average hospitalized COVID patients</span></span>
<span id="cb66-25"><a href="#cb66-25" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>avg_hosp_covid)  </span>
<span id="cb66-26"><a href="#cb66-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Lower bounds: about 400 (2020-2021), about 25 (2022-2024)  </span></span>
<span id="cb66-27"><a href="#cb66-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Peaks: Jan 2021 (1200), Sep 2021 (1300), Late Jan 2022 (900),  </span></span>
<span id="cb66-28"><a href="#cb66-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Sep 2022 (200), Jan 2023 (200), Sep 2023 (100), Jan 2024 (150)  </span></span>
<span id="cb66-29"><a href="#cb66-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-30"><a href="#cb66-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by average hospitalized flu patients</span></span>
<span id="cb66-31"><a href="#cb66-31" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>avg_hosp_flu)  </span>
<span id="cb66-32"><a href="#cb66-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Slight exponential increase from 0 to 60 (start to Nov 2022)  </span></span>
<span id="cb66-33"><a href="#cb66-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Noticeable peak in Jan 2023 (100), constant at 90 (2023)  </span></span>
<span id="cb66-34"><a href="#cb66-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Another peak in Jan 2024, then drops back to 100  </span></span>
<span id="cb66-35"><a href="#cb66-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-36"><a href="#cb66-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by average inpatient beds</span></span>
<span id="cb66-37"><a href="#cb66-37" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>avg_inpat_bed)  </span>
<span id="cb66-38"><a href="#cb66-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Slight increase followed by a tapered decrease (start to end of 2022)  </span></span>
<span id="cb66-39"><a href="#cb66-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Starts at 16,000, peaks at 19,000, then drops back to 16,000  </span></span>
<span id="cb66-40"><a href="#cb66-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Big jump at the start of 2023, lower at 19,500,  </span></span>
<span id="cb66-41"><a href="#cb66-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Peaks in March (20,500), drops to 20,000 (Aug)  </span></span>
<span id="cb66-42"><a href="#cb66-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Peaks again in Jan 2024 (20,600), then declines until April  </span></span>
<span id="cb66-43"><a href="#cb66-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-44"><a href="#cb66-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by average ICU beds</span></span>
<span id="cb66-45"><a href="#cb66-45" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>avg_icu_bed)  </span>
<span id="cb66-46"><a href="#cb66-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Starts at 2,400, peaks at 3,400 (Feb 2021)  </span></span>
<span id="cb66-47"><a href="#cb66-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Gradual decline to 3000 (Nov 2022), trough in Dec 2022 (2800)  </span></span>
<span id="cb66-48"><a href="#cb66-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Rises back to 3000 (Feb 2023), remains constant thereafter  </span></span>
<span id="cb66-49"><a href="#cb66-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-50"><a href="#cb66-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by average inpatient beds occupied</span></span>
<span id="cb66-51"><a href="#cb66-51" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>avg_inpat_bed_ocp, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">14000</span>, <span class="dv">17000</span>))  </span>
<span id="cb66-52"><a href="#cb66-52" aria-hidden="true" tabindex="-1"></a><span class="co"># Starts at 10000, rises to 13000 (Oct 2020)  </span></span>
<span id="cb66-53"><a href="#cb66-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Stays variable between 13000-15000 until Dec 2022  </span></span>
<span id="cb66-54"><a href="#cb66-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Jumps to 15000 (Jan 2023), peaks at 16000 (end of Jan)  </span></span>
<span id="cb66-55"><a href="#cb66-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Trough in July (15000), peaks again in Jan 2024 (16,500)  </span></span>
<span id="cb66-56"><a href="#cb66-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Declines to 15500 at the end of data collection  </span></span>
<span id="cb66-57"><a href="#cb66-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-58"><a href="#cb66-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot date by average ICU beds occupied</span></span>
<span id="cb66-59"><a href="#cb66-59" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>date, dat<span class="sc">$</span>avg_icu_bed_ocp, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">3000</span>))  </span>
<span id="cb66-60"><a href="#cb66-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Starts at about 1500, peaks at 2,600 (Jan 2021)  </span></span>
<span id="cb66-61"><a href="#cb66-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Remains fairly constant with seasonal variation (peaks in winter, troughs in summer) </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have general idea of how the data looks with time, lets look at the correlations in the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(dat <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>date, <span class="sc">-</span>state) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>())</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="co"># correlations of &gt;= 0.7 include: </span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co"># num_covid_admin and avg_hosp_covid have cor = 0.93</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># num_flu_admin and avg_hosp_flu have cor = 0.77,</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co"># avg_hosp_flu and avg_inpat_bed have cor = 0.73,</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="co"># avg_inpat_bed and avg_inpat_bed_ocp have cor = 0.89,</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co"># avg_icu_bed and avg_icu_bed_ocp have cor 0.70</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generate-synthetic-data" class="level2">
<h2 class="anchored" data-anchor-id="generate-synthetic-data">Generate synthetic data</h2>
<p>Per the encouragement in the instructions for this exercise, I asked ChatGPT to create my code. I first presented the code and text above and asked it to interpret it and provide an “ideal input” for actually simulating the data. It provided the following prompt:</p>
<p>“Generate a synthetic dataset that mirrors the statistical properties and temporal trends of real hospitalization data in Georgia from August 2020 to April 2024. The dataset should include the following variables:</p>
<ul>
<li><p>Week Ending Date: Weekly timestamps from 2020-08-08 to 2024-04-27.</p></li>
<li><p>Geographic Aggregation: Constant value “GA”.</p></li>
<li><p>Number of Hospitals Reporting Adult COVID-19 Admissions: Typically stable around 137-140, except an initial outlier at 87 in August 2020 and slight declines in later years.</p></li>
<li><p>Number of Hospitals Reporting Influenza Admissions: Initially low (0-2 for first 11 weeks), stabilizing around 120-139, with some seasonal variations.</p></li>
<li><p>Weekly Total Adult COVID-19 Admissions: Clear spikes in Jan-Feb 2021, Aug-Sep 2021, Jan 2022, with smaller spikes in Jul-Aug 2022, Jan 2023, and Jan 2024.</p></li>
<li><p>Weekly Total Influenza Admissions: Peaks in January, increasing year over year (25 in 2021, 50 in 2022, 80 in 2023, 800 in 2024).</p></li>
<li><p>Weekly Average Hospitalized COVID-19 ICU Patients: High peaks in Jan 2021 (), Sep 2021 (), and Jan 2022 (), then decreasing post-2022.</p></li>
<li><p>Weekly Average Hospitalized Influenza ICU Patients: Gradual increase until Nov 2022 (), peak in Jan 2023 (), stable at before another peak in Jan 2024.</p></li>
<li><p>Weekly Average Inpatient Beds: General increasing trend with fluctuations, peaking in early 2023 (,500), dropping in late 2023 before another peak in early 2024.</p></li>
<li><p>Weekly Average ICU Beds: Peaked at 3400 in Feb 2021, then a gradual decline stabilizing around 3000.</p></li>
<li><p>Weekly Average Inpatient Beds Occupied: Increased steadily until 2022, peaked in Jan 2023 (,000), then fluctuated seasonally.</p></li>
<li><p>Weekly Average ICU Beds Occupied: Seasonal peaks in winter, troughs in summer, high correlation with ICU bed availability.”</p></li>
</ul>
<p>I then asked ChatGPT to proceed with providing the code to produce the synthetic data. It gave me the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:patchwork':

    area</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define date range</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">ymd</span>(<span class="st">"2020-08-08"</span>), <span class="fu">ymd</span>(<span class="st">"2024-04-27"</span>), <span class="at">by =</span> <span class="st">"week"</span>)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dates)</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic reporting hospitals (with slight variations)</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>hosp_report_covid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">87</span>, <span class="fu">rep</span>(<span class="dv">139</span>, n <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>hosp_report_flu <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">11</span>), <span class="fu">rep</span>(<span class="dv">125</span>, n <span class="sc">-</span> <span class="dv">11</span>)) <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">5</span>)</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create seasonal trends</span></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>seasonal_covid <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> (<span class="fu">month</span>(dates) <span class="sc">/</span> <span class="dv">12</span>))</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>seasonal_flu <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> ((<span class="fu">month</span>(dates) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">12</span>))</span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Define mean values</span></span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>means <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1259.5</span>, <span class="fl">73.04</span>, <span class="fl">283.58</span>, <span class="fl">45.58</span>, <span class="dv">18361</span>, <span class="dv">3043</span>, <span class="dv">14415</span>, <span class="dv">2377</span>)</span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-19"><a href="#cb75-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Define standard deviations</span></span>
<span id="cb75-20"><a href="#cb75-20" aria-hidden="true" tabindex="-1"></a>sds <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">50</span>, <span class="dv">2000</span>, <span class="dv">300</span>, <span class="dv">1500</span>, <span class="dv">500</span>)</span>
<span id="cb75-21"><a href="#cb75-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-22"><a href="#cb75-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Define correlation matrix</span></span>
<span id="cb75-23"><a href="#cb75-23" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(</span>
<span id="cb75-24"><a href="#cb75-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.93</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>, <span class="fl">0.1</span>, <span class="fl">0.4</span>, <span class="fl">0.3</span>,</span>
<span id="cb75-25"><a href="#cb75-25" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">0.3</span>, <span class="fl">0.77</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>, <span class="fl">0.4</span>, <span class="fl">0.3</span>,</span>
<span id="cb75-26"><a href="#cb75-26" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.93</span>, <span class="fl">0.3</span>, <span class="dv">1</span>, <span class="fl">0.4</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="fl">0.4</span>,</span>
<span id="cb75-27"><a href="#cb75-27" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.3</span>, <span class="fl">0.77</span>, <span class="fl">0.4</span>, <span class="dv">1</span>, <span class="fl">0.73</span>, <span class="fl">0.5</span>, <span class="fl">0.4</span>, <span class="fl">0.3</span>,</span>
<span id="cb75-28"><a href="#cb75-28" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.2</span>, <span class="fl">0.3</span>, <span class="fl">0.3</span>, <span class="fl">0.73</span>, <span class="dv">1</span>, <span class="fl">0.7</span>, <span class="fl">0.89</span>, <span class="fl">0.6</span>,</span>
<span id="cb75-29"><a href="#cb75-29" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.1</span>, <span class="fl">0.2</span>, <span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="fl">0.7</span>, <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.7</span>,</span>
<span id="cb75-30"><a href="#cb75-30" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">0.5</span>, <span class="fl">0.4</span>, <span class="fl">0.89</span>, <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="fl">0.7</span>,</span>
<span id="cb75-31"><a href="#cb75-31" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.3</span>, <span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">0.3</span>, <span class="fl">0.6</span>, <span class="fl">0.7</span>, <span class="fl">0.7</span>, <span class="dv">1</span>),</span>
<span id="cb75-32"><a href="#cb75-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">8</span></span>
<span id="cb75-33"><a href="#cb75-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb75-34"><a href="#cb75-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-35"><a href="#cb75-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Make correlation matrix positive definite</span></span>
<span id="cb75-36"><a href="#cb75-36" aria-hidden="true" tabindex="-1"></a>cor_matrix_pd <span class="ot">&lt;-</span> <span class="fu">nearPD</span>(cor_matrix, <span class="at">corr =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>mat</span>
<span id="cb75-37"><a href="#cb75-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-38"><a href="#cb75-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate correlated synthetic data using multivariate normal distribution</span></span>
<span id="cb75-39"><a href="#cb75-39" aria-hidden="true" tabindex="-1"></a>cov_matrix <span class="ot">&lt;-</span> <span class="fu">diag</span>(sds) <span class="sc">%*%</span> <span class="fu">as.matrix</span>(cor_matrix_pd) <span class="sc">%*%</span> <span class="fu">diag</span>(sds)</span>
<span id="cb75-40"><a href="#cb75-40" aria-hidden="true" tabindex="-1"></a>synthetic_data <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(n, <span class="at">mu =</span> means, <span class="at">Sigma =</span> cov_matrix)</span>
<span id="cb75-41"><a href="#cb75-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-42"><a href="#cb75-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to data frame</span></span>
<span id="cb75-43"><a href="#cb75-43" aria-hidden="true" tabindex="-1"></a>dat_synth <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb75-44"><a href="#cb75-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">date =</span> dates,</span>
<span id="cb75-45"><a href="#cb75-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"GA"</span>,</span>
<span id="cb75-46"><a href="#cb75-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">hosp_report_covid =</span> <span class="fu">round</span>(hosp_report_covid),</span>
<span id="cb75-47"><a href="#cb75-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">hosp_report_flu =</span> <span class="fu">round</span>(hosp_report_flu),</span>
<span id="cb75-48"><a href="#cb75-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">num_covid_admin =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">1</span>] <span class="sc">+</span> seasonal_covid),</span>
<span id="cb75-49"><a href="#cb75-49" aria-hidden="true" tabindex="-1"></a>  <span class="at">num_flu_admin =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">2</span>] <span class="sc">+</span> seasonal_flu),</span>
<span id="cb75-50"><a href="#cb75-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">avg_hosp_covid =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">3</span>]),</span>
<span id="cb75-51"><a href="#cb75-51" aria-hidden="true" tabindex="-1"></a>  <span class="at">avg_hosp_flu =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">4</span>]),</span>
<span id="cb75-52"><a href="#cb75-52" aria-hidden="true" tabindex="-1"></a>  <span class="at">avg_inpat_bed =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">5</span>]),</span>
<span id="cb75-53"><a href="#cb75-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">avg_icu_bed =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">6</span>]),</span>
<span id="cb75-54"><a href="#cb75-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">avg_inpat_bed_ocp =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">7</span>]),</span>
<span id="cb75-55"><a href="#cb75-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">avg_icu_bed_ocp =</span> <span class="fu">round</span>(synthetic_data[, <span class="dv">8</span>])</span>
<span id="cb75-56"><a href="#cb75-56" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb75-57"><a href="#cb75-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-58"><a href="#cb75-58" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure values stay within realistic bounds</span></span>
<span id="cb75-59"><a href="#cb75-59" aria-hidden="true" tabindex="-1"></a>dat_synth <span class="ot">&lt;-</span> dat_synth <span class="sc">%&gt;%</span></span>
<span id="cb75-60"><a href="#cb75-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb75-61"><a href="#cb75-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_covid_admin =</span> <span class="fu">pmax</span>(num_covid_admin, <span class="dv">122</span>),</span>
<span id="cb75-62"><a href="#cb75-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_flu_admin =</span> <span class="fu">pmax</span>(num_flu_admin, <span class="dv">0</span>),</span>
<span id="cb75-63"><a href="#cb75-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_hosp_covid =</span> <span class="fu">pmax</span>(avg_hosp_covid, <span class="dv">28</span>),</span>
<span id="cb75-64"><a href="#cb75-64" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_hosp_flu =</span> <span class="fu">pmax</span>(avg_hosp_flu, <span class="dv">0</span>),</span>
<span id="cb75-65"><a href="#cb75-65" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_inpat_bed =</span> <span class="fu">pmax</span>(avg_inpat_bed, <span class="dv">12754</span>),</span>
<span id="cb75-66"><a href="#cb75-66" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_icu_bed =</span> <span class="fu">pmax</span>(avg_icu_bed, <span class="dv">2403</span>),</span>
<span id="cb75-67"><a href="#cb75-67" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_inpat_bed_ocp =</span> <span class="fu">pmax</span>(avg_inpat_bed_ocp, <span class="dv">10065</span>),</span>
<span id="cb75-68"><a href="#cb75-68" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_icu_bed_ocp =</span> <span class="fu">pmax</span>(avg_icu_bed_ocp, <span class="dv">1210</span>)</span>
<span id="cb75-69"><a href="#cb75-69" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb75-70"><a href="#cb75-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-71"><a href="#cb75-71" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows</span></span>
<span id="cb75-72"><a href="#cb75-72" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat_synth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        date state hosp_report_covid hosp_report_flu num_covid_admin
1 2020-08-08    GA                86              10            1143
2 2020-08-15    GA               139               3            1058
3 2020-08-22    GA               141              -6            1176
4 2020-08-29    GA               139              -3             754
5 2020-09-05    GA               139              -6            2391
6 2020-09-12    GA               141              11            3042
  num_flu_admin avg_hosp_covid avg_hosp_flu avg_inpat_bed avg_icu_bed
1            43            367           42         19299        3293
2           417            458          143         22447        3496
3             0            561           14         16353        2695
4           103            418          121         20512        3355
5            64           1117          102         19348        3084
6            31            900           10         14572        2403
  avg_inpat_bed_ocp avg_icu_bed_ocp
1             15625            3090
2             17691            3509
3             13328            2144
4             14948            2578
5             14974            2468
6             12839            1214</code></pre>
</div>
</div>
<p>In the following sections, I’ll compare the synthetic data with the real data and evaluate.</p>
</section>
<section id="variables-by-time" class="level2">
<h2 class="anchored" data-anchor-id="variables-by-time">Variables by time</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> hosp_report_covid), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> hosp_report_covid), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> hosp_report_flu), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> hosp_report_flu), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> num_covid_admin), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> num_covid_admin), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> num_flu_admin), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> num_flu_admin), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_hosp_covid), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_hosp_covid), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_hosp_flu), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_hosp_flu), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_inpat_bed), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_inpat_bed), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_icu_bed), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_icu_bed), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_inpat_bed_ocp), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_inpat_bed_ocp), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-9.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot real data and synthetic data to compare</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_icu_bed_ocp), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> dat_synth, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> avg_icu_bed_ocp), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-27-10.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Some of the variables are decent but most lack the more granular trends seen in the real data. Unfortunately, I was expecting this. The data we are working with are very unique in nature because they are from such a unique time. Surely generating data with more precise patterns is possible but it would require more equations.</p>
</section>
<section id="variable-distributions" class="level2">
<h2 class="anchored" data-anchor-id="variable-distributions">Variable distributions</h2>
<p>These plots correspond to the distribution plots of the real data in part 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_synth, <span class="fu">aes</span>(<span class="at">x=</span>num_covid_admin)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_synth, <span class="fu">aes</span>(<span class="at">x=</span>avg_hosp_covid)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_synth, <span class="fu">aes</span>(<span class="at">x=</span>num_flu_admin)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-28-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_synth, <span class="fu">aes</span>(<span class="at">x=</span>avg_hosp_flu)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-28-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat_synth, <span class="fu">aes</span>(<span class="at">x=</span>avg_icu_bed)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-28-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These plots are decent. None are extremely bad in comparison to the real data but none are great.</p>
</section>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary statistics</h2>
<p>These correspond to the summary statistics produced in part 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat_synth<span class="sc">$</span>hosp_report_covid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   86.0   138.0   139.0   138.7   140.0   142.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat_synth<span class="sc">$</span>hosp_report_flu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   -6.0   121.0   125.0   118.2   128.0   138.0 </code></pre>
</div>
</div>
<p>The summary statistics for these two variables in the synthetic data are actually pretty good! This is likely due to the fact that the synthetic data was largely based on such measurements. Though I find this interesting because we know from the plots above that the synthetic data isn’t a great representation of the real data.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>